# Generated by Django 5.1.6 on 2025-03-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_countrysafety_delete_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrysafety',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='countrysafety',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='countrysafety',
            name='capital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='countrysafety',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='countrysafety',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
