

services:
  db:
    image: postgres:17
    container_name: gtgo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coffeeandtv
      POSTGRES_DB: GTJ_GO
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - ./init-scripts:/docker-entrypoint-initdb.d
      
volumes:
  postgres-data: